[package]
authors = ["Nathan Hsiao <nathan40241@gmail.com>"]
name = "scheduler_fcfs"
description = "Provides first come first serve scheduling functionality"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.8"
spin = "0.9.4"
task = { path = "../task" }

[lib]
crate-type = ["rlib"]
